### PR TITLE
optimizations and small fixes... OPS Study command needs fixing (Null…

### PR DESCRIPTION
**Pull request by BitOfAByte**
…pointer exception)

### CODE REVIEW

**Comment by Tjens23** [comment]
Fixed ^^

**Review by VBPedersen — CHANGES_REQUESTED** [review]
Can't run

**Comment by BitOfAByte** [comment]
> Can't run

Runs for me lol... What java version u using?

**Review by VBPedersen — APPROVED** [review]
better now :)

**Review by VictorKPetersen — APPROVED** [review]
Ser godt ud!

**Pull request merged**
